version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: booking-service
    container_name: booking-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/bookingdb
    networks:
      - backend

networks:
  backend:
